apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean-dns-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgAdzPmeRmmo0+E9RsPsreeE9EWu/Z1nGpLy/82L7PyaONk4RaYsaHpOReTWP37BtngGmRnp/HjDSgwe8qYWr5oeT+uPtEfACo/mMy+vlyPBvT7TkWLykUV70FlmcXIVuqJLtEuERb391w9BdMpTzAu0oZPiXgmYdGnLYzlbzCtn5y1q7CxTmV9EgbaE14HWpQIyVlZwwtZD7wvAiyDO5iQo9c/PZT82GR0eJu6Un7xGszb3yB2aq44K7JYp3gE7dqmh9dJBHdT+WDgqELGRn+VZJc2YhO19+62D4LtjgpFV0YTUA38ITZSxn3HkzoXNe/lQpsT1q90CQWF0Sbcqe0EIZSUeRqg+tF1+l3wiBq48EX9YXYdXoMmaI9ESa7JgCwIBRD1ucP1KlVbelcO/oGlgOyiF0XHea6MiGGTyeONVMIFsOqQrCv5FhLAB8bx6S1wAigz36qPpHRgJ4bjU9QsF6eynzEzw3urlI4d0yKWZVVLIHYuSr4QY5qaMV5HVhs22UNk1zJIsSjEKmHDnftTI3O6xGIwzWwuegVOxgZ6RTrvK9xsDcMfzkNhaLDOGGpGNhWOCYXsVI0OVQKXJ+1lU974mPwapI/OeIZdSSj9ceERRrhr91nMfAxnl/CIUhD6YyyUcMjxhbK/5iIL5o0DZZ4GDTnv9M4rInL0xoUrJgqQ0vlr+9VIZRURSzm2q0VNHdL0aFjUqFgjCULIw6bQ71nTeXzeSZ8mSzM2KqHTcE4P0PbbslROGf6oISm+3yEL8o1CD8mZmadI7tatHo6KY8XtLef2ieA==
  template:
    metadata:
      name: digitalocean-dns-token-secret
      namespace: cert-manager
    type: Opaque
