apiVersion: v1
kind: Service
metadata:
  name: hbbs-service
spec:
  type: LoadBalancer
  selector:
    app: hbbs
  ports:
    - name: nat-test
      port: 21115
      targetPort: 21115
      protocol: TCP
    - name: tcp-hole-punch
      port: 21116
      targetPort: 21116
      protocol: TCP
    - name: udp-hole-punch
      port: 21116
      targetPort: 21116
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: hbbr-service
spec:
  type: LoadBalancer
  selector:
    app: hbbr
  ports:
    - name: tcp-relay
      port: 21117
      targetPort: 21117
      protocol: TCP
    - name: web-client-1
      port: 21118
      targetPort: 21118
      protocol: TCP
    - name: web-client-2
      port: 21119
      targetPort: 21119
      protocol: TCP
