apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of your deployment
  name: nginx-deployment
  # The namespace where this deployment will be created.
  # Change this to the namespace you want to deploy into.
  namespace: default
spec:
  # Run 2 replicas of the NGINX pod
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          # It's best practice to use a specific version instead of 'latest'
          image: nginx:1.25.3
          ports:
            - containerPort: 80
